### PR TITLE
Add support for nested routers as generated by express-generator

### LINKED ISSUE #300: Doesn't handle nested routers
So I can do a lot more with your version than https://github.com/vijay4495/express-routes-catalogue/blob/master/src/index.ts#L85-L92 but they handle the nested router as recommended by the express generator

```
app = express();
const indexRouter = express.Router();
indexRouter .get('/', (req, res) => res.send("OK"));
app.use('/', indexRouter);
```

I think look you just need to loop through middleware.handle.stack if it comes up.. I'll try to get a PR up

### PR DESCRIPTION
**Pull request by halkeye**
fixes #300

### CODE REVIEW

**Comment by halkeye** [comment]
okay, it doesn't handle app.use('/path', router). I guess thats why the other lib was processing the regex.

**Review by goloroden — APPROVED** [review]

**Comment by goloroden** [comment]
Hey @halkeye 👋

Thanks for the PR! It looks good, and it is basically ready to get merged.

However, before doing this I wanted to ask whether you would like to add yourself to the list of contributors in the `package.json` file? If so, just add another commit, if not, please let me know, so I can merge.

**Comment by halkeye** [comment]
Okay, handled the prefixed case that express-generator produces

borrowed the regex from express-routes-catalogue but there's probably an easier way to handle it now that you have tests for it.

also removed the forOwn/lodash as mentioned in #302 

I don't have any need to be added as a contributor.

**Review by goloroden — DISMISSED** [review]

**Comment by goloroden** [comment]
@halkeye Thanks for the update, I'll streamline a few things, and then merge this and publish a new version.

Thanks for your great help 🎉

**Review by goloroden — APPROVED** [review]

**Pull request merged**
