### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by RaianRaika**
Here is the bug fix for issue #1 .
Also add dual formating for URL output (regex and human-readable), and some docs added to project that cover the parts. for make documents more pretty, I Impliment some Defualts Error Class and throw them insted of pure Error.

### CODE REVIEW

**Comment by goloroden** [comment]
Hi 😊 

Thanks for sending this PR. As always, there are some things I would like you to change, so that it better matches our coding style.

To start with the two most obvious things:

- We don't use JSDoc or something like this, so can you please remove these comments?
- Can you please remove the various error classes?

**Comment by RaianRaika** [comment]
Hi :nerd_face: 
I really like this part, because learning new things,
about the JSDoc, so have usually should provide the docs on the codes in your opinion?

**Comment by goloroden** [comment]
From our experience, JSDoc tend to move away from the implementation over time, because one forgets to adjust one or the other. Things about the code (such as "why is the code as it is?" should be in inline comments), things relevant for the user ("how to use this code?") should be in the documentation, i.e. the `README.md`.

**Comment by goloroden** [comment]
I’m going to close this for now, but please feel free to open another PR with smaller changes.

**Pull request closed without merging**
